// Generated by CoffeeScript 1.7.1
var Marker, app;

Marker = (function() {
  function Marker(id, latlng) {
    this.id = id;
    this.latlng = latlng;
    this.start = null;
    this.end = null;
    this.glatlng = {
      lat: this.latlng.latitude,
      lng: this.latlng.longitude
    };
    this.icon = "/states/inactive.png";
    this.prevIcon = "/states/inactive.png";
    this.showWindow = false;
  }

  return Marker;

})();

app = angular.module('mapApp', ['google-maps', 'services']);

app.controller('infoController', [
  '$scope', 'sharedProperties', function($scope, sharedProperties) {
    $scope.onStartClick = function() {
      var id, props;
      props = sharedProperties.Properties();
      id = $scope.model.id;
      if (props.route.end === id) {
        sharedProperties.setEnd(-1);
      }
      return sharedProperties.setStart($scope.model.id);
    };
    $scope.onEndClick = function() {
      var id, props;
      props = sharedProperties.Properties();
      id = $scope.model.id;
      if (props.route.start === id) {
        sharedProperties.setStart(-1);
      }
      return sharedProperties.setEnd($scope.model.id);
    };
    return $scope.onStreetViewClick = function() {
      var currentMarker, properties;
      properties = sharedProperties.Properties();
      currentMarker = properties.markers[$scope.model.id];
      properties.panorama.setPosition(currentMarker.glatlng);
      return $scope.$emit("street-view-clicked");
    };
  }
]);

app.controller('mapController', [
  '$scope', '$compile', 'sharedProperties', 'markerService', function($scope, $compile, sharedProperties, markerService) {
    var latlngs;
    $scope.markers = [];
    $scope.map = {
      'center': {
        'latitude': 33.884388,
        'longitude': -117.641235
      },
      'zoom': 12,
      'local': sharedProperties.Properties(),
      'showTraffic': false,
      'showStreetView': true,
      'toggleStreetView': function() {
        return angular.element("#pano").slideToggle(400);
      },
      'toggleTrafficLayer': function() {
        return $scope.map.showTraffic = !$scope.map.showTraffic;
      },
      'mapOptions': {
        'panControl': false,
        'rotateControl': false,
        'streetViewControl': false,
        'zoomControlOptions': {
          'position': google.maps.ControlPosition.BOTTOM_LEFT
        }
      },
      'infoWindowOptions': {
        'pixelOffset': new google.maps.Size(0, -30)
      },
      'events': {
        'idle': function(map) {
          var addCloseStreetBtn, addTrafficBtn, loadStreetView;
          addTrafficBtn = function() {
            var el, element;
            element = document.createElement('div');
            el = angular.element(element);
            el.append('<button ng-click="map.toggleTrafficLayer()">Traffic</button>');
            $compile(el)($scope);
            return map.controls[google.maps.ControlPosition.TOP_RIGHT].push(el[0]);
          };
          addCloseStreetBtn = function(callback) {
            var el, element, panorama;
            element = document.createElement('div');
            el = angular.element(element);
            el.append('<button id="closeStreetView" ng-click="map.toggleStreetView()">Close</button>');
            $compile(el)($scope);
            panorama = sharedProperties.Properties().panorama;
            panorama.controls[google.maps.ControlPosition.TOP_RIGHT].push(el[0]);
            return callback();
          };
          loadStreetView = function(cb) {
            sharedProperties.setPanorama(map);
            return cb();
          };
          loadStreetView(function() {
            return addCloseStreetBtn(function() {
              return angular.element("#pano").slideToggle(800);
            });
          });
          return addTrafficBtn();
        }
      }
    };
    $scope.$on("street-view-clicked", function() {
      $scope.map.toggleStreetView();
      return console.log(angular.element('#pano').css('z-index', 1));
    });
    latlngs = [];
    latlngs.push({
      'latitude': 33.843801,
      'longitude': -117.717234
    });
    latlngs.push({
      'latitude': 33.826690,
      'longitude': -117.716419
    });
    latlngs.push({
      'latitude': 33.820415,
      'longitude': -117.716977
    });
    latlngs.forEach(function(element, index) {
      var marker;
      marker = new Marker(index, element);
      marker.close = function() {
        markerService.setMarkerDefault(this.model);
        return $scope.$apply();
      };
      marker.onClick = function() {
        $scope.map.local.markers.forEach(function(element) {
          return markerService.setMarkerDefault(element);
        });
        markerService.setMarkerStatus(this.model, "focused");
        $scope.id = this.model.id;
        return $scope.$apply();
      };
      return $scope.map.local.markers.push(marker);
    });
    return $scope.$watchCollection('map.local.route', function(newValues, oldValues, scope) {
      var endId, markers, startId;
      startId = newValues.start;
      endId = newValues.end;
      if ((startId === -1) && (endId === -1) || (startId === endId)) {
        if (oldValues.start === startId) {
          return sharedProperties.setStart(-1);
        }
        if (oldValues.end === endId) {
          return sharedProperties.setEnd(-1);
        }
      }
      markers = sharedProperties.Properties().markers;
      markers.forEach(function(marker) {
        if (marker.status === "start" || marker.status === "end") {
          return markerService.setMarkerStatus(marker, "inactive");
        }
      });
      sharedProperties.setMarkers(markers);
      markerService.setMarkerStatus(markers[startId], 'start');
      return markerService.setMarkerStatus(markers[endId], 'end');
    });
  }
]);
