// Generated by CoffeeScript 1.5.0
(function() {
  var Marker;

  Marker = (function() {

    function Marker(id, latlng) {
      this.id = id;
      this.latlng = latlng;
      this.start = null;
      this.end = null;
      this.glatlng = {
        lat: this.latlng.latitude,
        lng: this.latlng.longitude
      };
      this.icon = "states/inactive.png";
      this.prevIcon = "states/inactive.png";
      this.showWindow = false;
    }

    return Marker;

  })();

}).call(this);
